{{- if .Values.mysql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.reader.secret.name }}
data:
  endpoint: {{ "payments-mysql:3306" | b64enc | quote }}
  name: {{ "payments" | b64enc | quote }}
  username: {{ "payments_user" | b64enc | quote }}
  password: {{ "default_password" | b64enc | quote }}
{{- end }}