AWSTemplateFormatVersion: 2010-09-09
Description: Watchn UI service Elastic Beanstalk application

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  VpcId:
    Description: VPC ID
    Type: 'AWS::EC2::VPC::Id'

  PrivateSubnetIds:
    Description: Private Subnet IDs
    Type: String

  PublicSubnetIds:
    Description: Public Subnet IDs
    Type: String

  ServiceRoleArn:
    Description: Elastic Beanstalk Service Role ARN
    Type: String

  CartsEndpoint:
    Description: Carts service endpoint
    Type: String

  CatalogEndpoint:
    Description: Catalog service endpoint
    Type: String

  OrdersEndpoint:
    Description: Orders service endpoint
    Type: String

  CheckoutEndpoint:
    Description: Checkout service endpoint
    Type: String

  AssetsEndpoint:
    Description: Assets service endpoint
    Type: String

Resources:
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub '${EnvironmentName}-ui'
      Description: Watchn UI service

  Version:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref Application
      SourceBundle: ../packages/ui.zip

  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref Application
      EnvironmentName: watchn-ui
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: AWS_REGION
          Value: !Ref AWS::Region
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENDPOINTS_CARTS
          Value: !Ref CartsEndpoint
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENDPOINTS_CATALOG
          Value: !Ref CatalogEndpoint
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENDPOINTS_ORDERS
          Value: !Ref OrdersEndpoint
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENDPOINTS_CHECKOUT
          Value: !Ref CheckoutEndpoint
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENDPOINTS_ASSETS
          Value: !Ref AssetsEndpoint
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Ref ServiceRoleArn
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: !Ref VpcId
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: !Ref PrivateSubnetIds
        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: !Ref PublicSubnetIds
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerType
          Value: application
      PlatformArn: !Sub arn:aws:elasticbeanstalk:${AWS::Region}::platform/Corretto 11 running on 64bit Amazon Linux 2/3.1.2
      VersionLabel: !Ref Version

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Role

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
      Path: /

Outputs:
  Endpoint:
    Description: Service endpoint
    Value: !Sub 'http://${Environment.EndpointURL}'