awsRegion: ${region}

rbac:
  create: true
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: "${role_arn}"

autoDiscovery:
  clusterName: ${cluster_name}
  enabled: true

extraArgs:
  expander: least-waste
  balance-similar-node-groups: true
  skip-nodes-with-system-pods: false