server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - ${domain}

alertmanager.enabled: false
pushgateway.enabled: false
nodeExporter.enabled: false