apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: nip-issuer
    kind: ClusterIssuer
  commonName: argocd.91.185.86.78.sslip.io
  dnsNames:
  - argocd.91.185.86.78.sslip.io
