apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nip-issuer
  namespace: certmanager
spec:
  acme:
    email: jora450000@ya.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: nip-issuer
    solvers:
     - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: nip-issuer1
 namespace: certmanager
spec:
 acme:
   email: jora450000@ya.ru
   # We use the staging server here for testing to avoid hitting
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: nip-issuer1
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik
