ingress:
  enabled: ${ingress_enabled}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - ${domain}
  tls:
    - secretName: watchn-ingress-tls
      hosts:
        - ${domain}

istio:
  enabled: ${istio_enabled}
  hosts:
    - ${domain}
  tls:
    secretName: watchn-ingress-tls
    hosts:
    - ${domain}
    issuer:
      name: letsencrypt-prod
      kind: ClusterIssuer