version: '3.4'

services:
  orders:
    build:
      context: .
      dockerfile: ../../images/java17/Dockerfile
      args:
        JAR_PATH: target/orders-0.0.1-SNAPSHOT.jar
    image: microservices-demo/orders
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=mysql,activemq
      - SPRING_DATASOURCE_WRITER_URL=jdbc:mysql://orders-db:3306/orders
      - SPRING_DATASOURCE_WRITER_USERNAME=orders_user
      - SPRING_DATASOURCE_WRITER_PASSWORD=default_password
      - SPRING_DATASOURCE_READER_URL=jdbc:mysql://orders-db:3306/orders
      - SPRING_DATASOURCE_READER_USERNAME=orders_user
      - SPRING_DATASOURCE_READER_PASSWORD=default_password
      - SPRING_DATASOURCE_WRITER_MAXIMUMPOOLSIZE=20
      - SPRING_ACTIVEMQ_BROKERURL=tcp://activemq:61616
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s

  orders-db:
    image: mysql:5.7
    hostname: orders-db
    restart: always
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=orders
      - MYSQL_USER=orders_user
      - MYSQL_PASSWORD=default_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -pmy-secret-pw -e 'SELECT 1 cache'"]
      interval: 1s
      timeout: 3s
      retries: 30

  activemq:
    build:
      context: .
      dockerfile: ../../images/activemq/Dockerfile
    image: watchn/activemq
    hostname: activemq
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
  
