version: '3.4'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8.3
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    logging:
      driver: none

  grafana:
    image: grafana/grafana:7.3.7
    networks:
      - grafana
    ports:
      - "8888:3000"
    cap_add:
      - CAP_NET_BIND_SERVICE
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    logging:
      driver: none
    volumes:
      - ./provisioning/:/etc/grafana/provisioning/

  k6:
    image: loadimpact/k6:0.30.0
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=${K6_OUT}
      - WATCHN_BASE_URL=${WATCHN_BASE_URL}
      - WATCHN_REGION=${WATCHN_REGION}
      - WATCHN_TARGET=${WATCHN_TARGET}
      - WATCHN_DURATION=${WATCHN_DURATION}
      - WATCHN_FETCH=${WATCHN_FETCH}
    command: run /js/script.js
    volumes:
      - ./js:/js