definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  model.PaymentIntent:
    properties:
      amount:
        type: integer
      cartId:
        type: string
      clientSecret:
        type: string
      currency:
        type: string
      expiresMonth:
        type: integer
      expiresYear:
        type: integer
      last4:
        type: string
      orderId:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This API serves the product payments
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Payments API
  version: "1.0"
paths:
  /client-secret/{id}:
    get:
      consumes:
      - application/json
      description: Get payment intent by cart ID
      parameters:
      - description: Cart ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.PaymentIntent'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get payment intent by cart ID
      tags:
      - payments
swagger: "2.0"
